### Numpy
- package
    - collection of modules
- Numpy
    - Numerical Python one of the most important data 
        science packages
     - used for scientific calculation
 - np.array()
 - np.arange()
 - np.random()
     - np.random.random()
     - np.random.randint()

In [1]:
import numpy as np
ar=np.array([[1,2,3],[4,5,6]]) # using list of lists
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
ar.dtype # datatype of array

dtype('int32')

In [3]:
ar2=np.array([(5,6,7),(8,6,1)]) # using list of tuples
ar2

array([[5, 6, 7],
       [8, 6, 1]])

In [4]:
ar2.size # no.of elements in the elements

6

In [5]:
ar3=np.array(([1,2,3],[4,5,6])) # using tuple of lists
ar3

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
ar3.itemsize # used to find the element size in array

4

In [15]:
print(ar3.shape) # giving no.of rows and columns
print(ar3.ndim) # dimensions
print(ar3.max()) # max element in the array4
print(np.max(ar3)) # using np.max()
print(ar3.min()) # min element
print(np.min(ar3)) # using np
print(ar3.sum()) # finding the sum of elements
print(np.sum(ar3))#find the sum using np using sum() method
print(type(ar3))# type

(2, 3)
2
6
6
1
1
21
21
<class 'numpy.ndarray'>


### Arrangement of Array

np.arange(,,)

np.arange(,,,)

np.arange().reshape()

np.linspace(,,,)

np.ones(,,,)

np.zeros()

np.full(,,,)

np.eye(,)

np.diag(ar)

np.diag([5,6,7])



In [18]:
iden=np.eye(3) #creating identity matrix
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
z=np.zeros((3,4)) # no.of rows and columns
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
f=np.full((2,3),5) 
f

array([[5, 5, 5],
       [5, 5, 5]])

In [24]:
np.diag(ar) # giving diagnoal elements

array([1, 5])

In [25]:
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
print(type(range(1,10)))

<class 'range'>


In [28]:
x=12
print(type(x))

<class 'int'>


In [39]:
r=np.array(range(10)) # creating array using range() method
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr=np.arange(10,20,3)
arr

array([10, 13, 16, 19])

In [31]:
print()

In [35]:
for num in range(10):
    print(num,end=" ")

0 1 2 3 4 5 6 7 8 9 

In [37]:
for num in range(10,20):
    print(num,end=" ")

10 11 12 13 14 15 16 17 18 19 

In [38]:
for num in range(10,30,3):
    print(num,end=" ")

10 13 16 19 22 25 28 

In [41]:
#create an array using range(lw,up,step_count)
r2=np.array(range(10,50,3))
print(r2)

[10 13 16 19 22 25 28 31 34 37 40 43 46 49]


In [43]:
r3=np.arange(10,20)
r3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [53]:
print(np.arange(6).reshape(2,3)) # aranging array of 5 elements
print(np.arange(4,20,3)) # aranging the array using  step count
print(np.arange(20,4,-2)) # reverse order from 20 to 4 with diff -2
print(np.arange(3,4,0.2)) # with 0.2 diff
print(np.arange(2.5,10,0.75)) # with 0.75 diff

[[0 1 2]
 [3 4 5]]
[ 4  7 10 13 16 19]
[20 18 16 14 12 10  8  6]
[3.  3.2 3.4 3.6 3.8]
[2.5  3.25 4.   4.75 5.5  6.25 7.   7.75 8.5  9.25]


In [64]:
print(np.arange(25).reshape(5,5)) # representing no.of rows and columns
print("......")
print(np.arange(32).reshape(8,-1)) # representing no.of rows
print("........")
print(np.arange(30).reshape(-1,5))
print('..........')
print(np.arange(20),(4,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
......
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
........
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
..........
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] (4, 5)


### np.random()
- Generates random values in b/w a range
- Sub modules in random()
    - np.random.randint(6)
    - np.random.randint(1,10)
    - np.random.randint(10,50,(2,3))
    - np.random.random((2,3))
    - np.random.rand(2,3)
    - np.random.randn(3,4)

In [72]:
print(np.random.randint(6))
print('....')
print(np.random.randint(2,10))
print('.....')
print(np.random.randint(20,40,5)) # row matrix of size 5 with random values from 20 to 40
print('......')
print(np.random.randint(10,100,(3,4))) # 3rows and 4 columns
print("........")
print(np.random.rand(2,3)) # it is of size 2*3 array
print(np.random.randn(2,3))

4
....
9
.....
[30 29 22 23 38]
......
[[17 64 45 31]
 [50 29 42 26]
 [40 25 65 34]]
........
[[0.5839618  0.01000408 0.88351575]
 [0.55544623 0.57963075 0.34750732]]
[[-0.64112562 -0.75020804 -0.11638591]
 [ 2.43182565  0.44136725 -0.13045322]]


In [77]:
rn=np.random.randint(10,100,(4,5))
rn

array([[47, 75, 87, 96, 83],
       [32, 30, 39, 19, 21],
       [26, 27, 67, 72, 47],
       [38, 41, 72, 14, 26]])

##### Index based Slicing
- [row,col]
    - [2:,:4]

In [78]:
rn

array([[47, 75, 87, 96, 83],
       [32, 30, 39, 19, 21],
       [26, 27, 67, 72, 47],
       [38, 41, 72, 14, 26]])

In [81]:
rn[1:,2:]

array([[39, 19, 21],
       [67, 72, 47],
       [72, 14, 26]])

In [80]:
rn[:,1:4]

array([[75, 87, 96],
       [30, 39, 19],
       [27, 67, 72],
       [41, 72, 14]])

In [84]:
rn[0:4:2]

array([[47, 75, 87, 96, 83],
       [26, 27, 67, 72, 47]])

In [83]:
rn

array([[47, 75, 87, 96, 83],
       [32, 30, 39, 19, 21],
       [26, 27, 67, 72, 47],
       [38, 41, 72, 14, 26]])

In [85]:
rn[2][4]

47

In [86]:
li=[1,2,3]
li2=[4,5,6]
print(li+li2)

[1, 2, 3, 4, 5, 6]


In [91]:
a=np.array(li)
a2=np.array(li2)
print(a+a2)
print(a*a2)
print(a/a2)
print(np.add(a,a2))

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[5 7 9]


#### Stacking
- Arranging one by one
- It is of 2 types:
    - hstack
    - vstack

In [109]:
b1=np.random.randint(1,10,(2,2))
b2=np.random.randint(1,10,(2))
print(b1)
print(b2)

[[7 9]
 [6 3]]
[6 3]


In [112]:
b3=np.random.randint(1,10,(2,1))
print(b3)
np.hstack((b3,b1))

[[4]
 [9]]


array([[4, 7, 9],
       [9, 6, 3]])

In [114]:
np.log(5)

1.6094379124341003

In [115]:
np.log(1)

0.0

In [116]:
np.log2(10)

3.321928094887362

In [117]:
np.log2(2)

1.0

In [118]:
np.exp(2)

7.38905609893065

In [119]:
np.exp(2)-1

6.38905609893065

In [120]:
np.mean(rn)

47.95

In [121]:
np.std(rn)

24.73757263758916

In [122]:
a.dot(a2)

32

### Pandas
- package for data analysis and manipulation
    - Series
    - DataFrame

In [1]:
import pandas as pd
pd.Series(['hi','hello','hey'])

0       hi
1    hello
2      hey
dtype: object