### Numpy
- It is a general purpose array processing object
- fundamental package for scientific computaion in python
- provides multidimenesional array objects and tools for these arrays
- Various Features:
    - Sophisticated Functions
    - Tools for integrating C/C++ and Fortran Code
    - Fourier Transform, mean standard deviation , linear algebra etc..
        - Besides calculation , works as an N-Dimensional container of generic data

#### Installation Process:
- pip install numpy
- import numpy

####  Array Creation
- How to create arrays ?
    - We can create arrys by using tuples and lists

In [2]:
import numpy as np
ar=np.array((1,2,3))
print(ar)

[1 2 3]


In [7]:
ar3=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(ar3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
ar4=np.array([[1,2,3],[45,67,89],[47,82,93]])
print(ar4)

[[ 1  2  3]
 [45 67 89]
 [47 82 93]]


In [20]:
print(ar4.dtype)

int32


####  Working with Numpy


In [11]:
z=np.zeros((2,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
o=np.ones((3,6))
print(o)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [16]:
f=np.full((3,5),9)
print(f)

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


####  random()
- Generates random values in a given range
- Syntax:
    - random(a,b)

In [26]:
r=np.random.rand(2,3)
print(r)

[[0.19137985 0.23125115 0.90043296]
 [0.52456393 0.71406946 0.95652718]]


In [28]:
rn=np.random.randn(2,2)
print(rn)

[[ 0.90400401 -0.57735518]
 [-1.9564473   0.21579253]]


In [ ]:
import numpy as np
ri=np.random.randint(2,10)
print(ri)

8


In [35]:
arr=np.arange(1,50,4)
print(arr)

[ 1  5  9 13 17 21 25 29 33 37 41 45 49]


In [47]:
ls=np.linspace(1,10,4)
print(ls)

[ 1.  4.  7. 10.]


###  Array Slicing

In [48]:
sl = np.array([[-1, 2, 0, 4], [4, -0.5, 6, 0], [2, 0, 7, 8],[3, -7, 4, 2.0]])
print(sl)

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.   0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [49]:
print(sl[2:])

[[ 2.  0.  7.  8.]
 [ 3. -7.  4.  2.]]


In [51]:
print(sl[:2])

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]]


In [52]:
print(sl[::])

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.   0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [57]:
print(sl[::-1])
print(sl)

[[ 3.  -7.   4.   2. ]
 [ 2.   0.   7.   8. ]
 [ 4.  -0.5  6.   0. ]
 [-1.   2.   0.   4. ]]
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.   0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [58]:
print(sl[:2,1:])

[[ 2.   0.   4. ]
 [-0.5  6.   0. ]]


In [69]:
print(sl.reshape(2,4,2))

[[[-1.   2. ]
  [ 0.   4. ]
  [ 4.  -0.5]
  [ 6.   0. ]]

 [[ 2.   0. ]
  [ 7.   8. ]
  [ 3.  -7. ]
  [ 4.   2. ]]]


In [63]:
arr = np.array([[1, 2, 3, 4], [5, 2, 4, 2], [1, 2, 0, 1]])
print(arr)

[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]


In [64]:
print(arr.reshape(2,3,2))

[[[1 2]
  [3 4]
  [5 2]]

 [[4 2]
  [1 2]
  [0 1]]]


In [70]:
fl=np.array([[1,2,3],[5,6,7],[77,54,76]])
print(fl.flatten())

[ 1  2  3  5  6  7 77 54 76]


####  Basic Operations

In [71]:
print(sl+3)

[[ 2.   5.   3.   7. ]
 [ 7.   2.5  9.   3. ]
 [ 5.   3.  10.  11. ]
 [ 6.  -4.   7.   5. ]]


In [72]:
print(sl[::-1]+4)

[[ 7.  -3.   8.   6. ]
 [ 6.   4.  11.  12. ]
 [ 8.   3.5 10.   4. ]
 [ 3.   6.   4.   8. ]]


In [78]:
print(np.sum(sl))

33.5


In [79]:
print(sl.sum())

33.5


In [92]:
print(sum(sl))

[ 8.  -5.5 17.  14. ]


In [81]:
print(np.min(sl))

-7.0


In [93]:
print(np.max(sl))

8.0


####  Scientific Calculations

In [83]:
print(np.mean(sl))

2.09375


In [84]:
print(np.std(sl))

3.518783303572415


In [86]:
print(sl.T)

[[-1.   4.   2.   3. ]
 [ 2.  -0.5  0.  -7. ]
 [ 0.   6.   7.   4. ]
 [ 4.   0.   8.   2. ]]


In [88]:
print(np.sin(arr))

[[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427  0.90929743 -0.7568025   0.90929743]
 [ 0.84147098  0.90929743  0.          0.84147098]]


In [90]:
print(np.exp(sl))

[[3.67879441e-01 7.38905610e+00 1.00000000e+00 5.45981500e+01]
 [5.45981500e+01 6.06530660e-01 4.03428793e+02 1.00000000e+00]
 [7.38905610e+00 1.00000000e+00 1.09663316e+03 2.98095799e+03]
 [2.00855369e+01 9.11881966e-04 5.45981500e+01 7.38905610e+00]]


In [91]:
print(np.sqrt(sl))

[[       nan 1.41421356 0.         2.        ]
 [2.                nan 2.44948974 0.        ]
 [1.41421356 0.         2.64575131 2.82842712]
 [1.73205081        nan 2.         1.41421356]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


In [95]:
dtypes = [('name', str), (454565, int), (6567.78, float)] 
print(dtypes)

[('name', <class 'str'>), (454565, <class 'int'>), (6567.78, <class 'float'>)]


In [ ]:
print(np.add(m1,m2))