### Numpy
- General pupose Array processing package
- Provides high performance multidimensional object and tools for these arrays
- Fundamental package for scientic computation in Python
    - Various Features:
        - A powerful N-dimensional array object
        - Sophisticated functions
        - Tools for integrating C/C++ and Fortran code
        - linear algebra, Fourier Transform and random number capabilites
    - Besides this scientic calculation--> Works as an N-dimensional array container of generic data
        

#### Installation process:
- pip install numpy
- import numpy


#### Working with Numpy

##### Array:
- Colletion of similar items/ collection of elements of the same data type
- index->tuple of +ve integers

#### Array Creation

In [2]:
import numpy as np
ar=np.array((12,34,45))
print(ar)

[12 34 45]


In [6]:
import numpy as np
ar2=np.array([(1,2,3),(4,5,6),(7,8,9),(4,9,3)])
print(ar2)
print(ar2.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [4 9 3]]
int32
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [4 9 3]]
int32
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [4 9 3]]
int32


In [2]:
import numpy as np
ar3=np.array([[1,2,3],[5,6,7],[8,9,3]])
print(ar3)

[[1 2 3]
 [5 6 7]
 [8 9 3]]


In [6]:
z=np.zeros((3,4))   # fills with 0s
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
o=np.ones((2,3))    # fills the entire matrix with 1s
print(o)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
f=np.full((2,3),8)    ## Fills the array with 3rd arguement
print(f)
print(f.dtype)

[[8 8 8]
 [8 8 8]]
int32
[[8 8 8]
 [8 8 8]]
int32
[[8 8 8]
 [8 8 8]]
int32


In [10]:
r=np.random.rand(2,4)  # Generates random no.s of 2 rows and 4 columns
print(r)

[[0.91360017 0.85290984 0.07346963 0.15828493]
 [0.32243369 0.9022243  0.52916008 0.08634637]]
[[0.91360017 0.85290984 0.07346963 0.15828493]
 [0.32243369 0.9022243  0.52916008 0.08634637]]
[[0.91360017 0.85290984 0.07346963 0.15828493]
 [0.32243369 0.9022243  0.52916008 0.08634637]]


In [11]:
r2=np.random.randint(2,10) # Gives random int in a range
print(r2)

3
3
3


In [12]:
r3=np.arange(1,30,4)   # arrange the no.s in a list with a diff of step count
print(r3)

[ 1  5  9 13 17 21 25 29]
[ 1  5  9 13 17 21 25 29]
[ 1  5  9 13 17 21 25 29]


In [17]:
l=np.linspace(1,5,8) # Creates a sequence of 8 values in a range 1 to 5 
print(l)

[1.         1.57142857 2.14285714 2.71428571 3.28571429 3.85714286
 4.42857143 5.        ]
[1.         1.57142857 2.14285714 2.71428571 3.28571429 3.85714286
 4.42857143 5.        ]
[1.         1.57142857 2.14285714 2.71428571 3.28571429 3.85714286
 4.42857143 5.        ]


In [45]:
arr = np.array([[1, 2, 3, 4], [5, 2, 4, 2], [1, 2, 0, 1]])
print(arr)

[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]


In [47]:
re=arr.reshape(2,3,2)
print(re)

[[[1 2]
  [3 4]
  [5 2]]

 [[4 2]
  [1 2]
  [0 1]]]


In [18]:
fl=np.array([[1,2,3],[5,6,7],[77,54,76]])
print(fl.flatten())

[ 1  2  3  5  6  7 77 54 76]
[ 1  2  3  5  6  7 77 54 76]
[ 1  2  3  5  6  7 77 54 76]


#### Array Slicing
- Syntax:
- [f,l]
- ar[r:c]

In [52]:
sl = np.array([[-1, 2, 0, 4], [4, -0.5, 6, 0], [2, 0, 7, 8],[3, -7, 4, 2.0]])
print(sl)

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [19]:
##print(sl[2:])

NameError: name 'sl' is not defined

NameError: name 'sl' is not defined

NameError: name 'sl' is not defined

In [56]:
print(sl[::])

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [54]:
print(sl[::-1])

[[ 3.  -7.   4.   2. ]
 [ 2.6  0.   7.   8. ]
 [ 4.  -0.5  6.   0. ]
 [-1.   2.   0.   4. ]]


In [57]:
print(sl[:2,1::])   ## Giving first 2 rows with columns from 1st index

[[ 2.   0.   4. ]
 [-0.5  6.   0. ]]


In [59]:
print(sl[::,:2])  # all rows ending with 2nd index

[[-1.   2. ]
 [ 4.  -0.5]
 [ 2.6  0. ]
 [ 3.  -7. ]]


In [8]:
cond = sl > 2# cond is a boolean array 
temp = sl[cond] 
print(temp)

[4.  4.  6.  2.6 7.  8.  3.  4. ]


####  Basic Operations

In [65]:
print(sl+9)## adding 9 to every element in the array

[[ 8.  11.   9.  13. ]
 [13.   8.5 15.   9. ]
 [11.6  9.  16.  17. ]
 [12.   2.  13.  11. ]]


In [21]:
import numpy as np
sl = np.array([[-1, 2, 0, 4], [4, -0.5, 6, 0], [2, 0, 7, 8],[3, -7, 4, 2.0]])
print(sl)
print(sl-2)

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.   0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
[[-3.   0.  -2.   2. ]
 [ 2.  -2.5  4.  -2. ]
 [ 0.  -2.   5.   6. ]
 [ 1.  -9.   2.   0. ]]
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.   0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
[[-3.   0.  -2.   2. ]
 [ 2.  -2.5  4.  -2. ]
 [ 0.  -2.   5.   6. ]
 [ 1.  -9.   2.   0. ]]
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.   0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
[[-3.   0.  -2.   2. ]
 [ 2.  -2.5  4.  -2. ]
 [ 0.  -2.   5.   6. ]
 [ 1.  -9.   2.   0. ]]


In [68]:
print(sl*3)

[[ -3.    6.    0.   12. ]
 [ 12.   -1.5  18.    0. ]
 [  7.8   0.   21.   24. ]
 [  9.  -21.   12.    6. ]]


In [69]:
print(sl*sl)

[[ 1.    4.    0.   16.  ]
 [16.    0.25 36.    0.  ]
 [ 6.76  0.   49.   64.  ]
 [ 9.   49.   16.    4.  ]]


In [70]:
print(sl.T)

[[-1.   4.   2.6  3. ]
 [ 2.  -0.5  0.  -7. ]
 [ 0.   6.   7.   4. ]
 [ 4.   0.   8.   2. ]]


In [71]:
print(sl.max())

8.0


In [72]:
print(sl.min())

-7.0


In [22]:
print(sl.sum())

33.5
33.5
33.5


In [23]:
print(sum(sl))

[ 8.  -5.5 17.  14. ]
[ 8.  -5.5 17.  14. ]
[ 8.  -5.5 17.  14. ]


In [74]:
print(np.sum(sl))

34.1


In [79]:
print(sl+r2)

[[-3.   0.  -2.   2. ]
 [ 2.  -2.5  4.  -2. ]
 [ 0.6 -2.   5.   6. ]
 [ 1.  -9.   2.   0. ]]


In [ ]:
2*2 3*2

In [82]:
print(sl.dot(r2))   # product of 2 arrays

[[ -2.    4.    0.    8. ]
 [  8.   -1.   12.    0. ]
 [  5.2   0.   14.   16. ]
 [  6.  -14.    8.    4. ]]


In [87]:
print(np.sin(sl))

[[-0.84147098  0.90929743  0.         -0.7568025 ]
 [-0.7568025  -0.47942554 -0.2794155   0.        ]
 [ 0.51550137  0.          0.6569866   0.98935825]
 [ 0.14112001 -0.6569866  -0.7568025   0.90929743]]


In [88]:
e = np.array([0, 1, 2, 3]) 
print ("Exponent of array elements:", np.exp(sl)) 

Exponent of array elements: [[3.67879441e-01 7.38905610e+00 1.00000000e+00 5.45981500e+01]
 [5.45981500e+01 6.06530660e-01 4.03428793e+02 1.00000000e+00]
 [1.34637380e+01 1.00000000e+00 1.09663316e+03 2.98095799e+03]
 [2.00855369e+01 9.11881966e-04 5.45981500e+01 7.38905610e+00]]


In [90]:
print(np.sqrt(sl))

[[       nan 1.41421356 0.         2.        ]
 [2.                nan 2.44948974 0.        ]
 [1.61245155 0.         2.64575131 2.82842712]
 [1.73205081        nan 2.         1.41421356]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


In [92]:
st = np.array([[1, 4, 2],[3, 4, 6],[0, -1, 5]]) 
print(np.sort(st))

[[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]


In [24]:
dtypes = [('name', str), (454565, int), (6567.78, float)] 
print(dtypes)

[('name', <class 'str'>), (454565, <class 'int'>), (6567.78, <class 'float'>)]
[('name', <class 'str'>), (454565, <class 'int'>), (6567.78, <class 'float'>)]
[('name', <class 'str'>), (454565, <class 'int'>), (6567.78, <class 'float'>)]


In [100]:
print(np.add(arr,r3))

ValueError: operands could not be broadcast together with shapes (3,4) (8,) 

In [5]:
import numpy as np
sl = np.array([[-1, 2, 0, 4], [4, -0.5, 6, 0], [2.6, 0, 7, 8],[3, -7, 4, 2.0]])
print(sl)

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [6]:
print(np.mean(sl))

2.13125


In [7]:
print(np.std(sl))

3.520780941424786


In [ ]:
import numpy as np
ar=np.array([1,2,3,4])
print(ar)

In [4]:
li=[1,2,3,4]
li

[1, 2, 3, 4]

[1, 2, 3, 4]

[1, 2, 3, 4]

In [7]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,0,4,3],[8,5,3,1]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]
 [9 0 4 3]
 [8 5 3 1]]
[[1 2 3 4]
 [5 6 7 8]
 [9 0 4 3]
 [8 5 3 1]]
[[1 2 3 4]
 [5 6 7 8]
 [9 0 4 3]
 [8 5 3 1]]
