In [1]:
import numpy as np
ar=np.array((1,2,3))
print(ar)

[1 2 3]


In [2]:
li=[1,2,3]
print(li)

[1, 2, 3]


In [3]:
ar2=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(ar2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
ar3=np.array([[12,34,5],[76,34,2],[9,6,3]])
print(ar3)

[[12 34  5]
 [76 34  2]
 [ 9  6  3]]


In [9]:
st=input()
#print(st)
rev=st[::-1]
print(st)
print(rev)

pvp students are good at skills but...
pvp students are good at skills but...
...tub slliks ta doog era stneduts pvp
