In [173]:
import datetime
d=datetime.datetime.now()

In [174]:
d.year

2019

In [175]:
d.day

21

In [176]:
d.date

<function datetime.date>

In [177]:
d.month

11

In [178]:
d.minute

50

In [179]:
d.hour

14

In [180]:
d.today() # today date metho

datetime.datetime(2019, 11, 21, 14, 50, 24, 398341)

In [181]:
d.time() # time function

datetime.time(14, 50, 23, 848950)

In [182]:
dir(d)

['__add__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rsub__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 'astimezone',
 'combine',
 'ctime',
 'date',
 'day',
 'dst',
 'fold',
 'fromisoformat',
 'fromordinal',
 'fromtimestamp',
 'hour',
 'isocalendar',
 'isoformat',
 'isoweekday',
 'max',
 'microsecond',
 'min',
 'minute',
 'month',
 'now',
 'replace',
 'resolution',
 'second',
 'strftime',
 'strptime',
 'time',
 'timestamp',
 'timetuple',
 'timetz',
 'today',
 'toordinal',
 'tzinfo',
 'tzname',
 'utcfromtimestamp',
 'utcnow',
 'utcoffset',
 'utctimetuple',
 'weekday',
 'year']

In [183]:
d.weekday()

3

In [184]:
d.tzname()

In [185]:
d.date()

datetime.date(2019, 11, 21)

In [186]:
d.second

23

In [187]:
import calendar as cal
cl=cal.month(2019,11)
print(cl)

   November 2019
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30



In [188]:
cal.monthrange(2019,7) #Mkonth of July has 31 days

(0, 31)

In [189]:
cal.monthrange(2019,12)

(6, 31)

In [190]:
cal.year(2019)

AttributeError: module 'calendar' has no attribute 'year'

In [ ]:
cal.weekday(2019,11,21)

In [ ]:
cal.monthrange(2020,1)

In [ ]:
d.max

In [ ]:
dir(cal)

In [ ]:
cal.prmonth(2019,11)

In [ ]:
cal.prweek()

In [ ]:
cal.leapdays(2000,2020)

In [ ]:
cal.isleap(2020)

In [ ]:
cal.isleap(2013)

In [ ]:
import time
local_time=time.localtime(time.time())
print(local_time)

In [ ]:
from datetime import date
today=date.today()
today

In [ ]:
d.today()

In [ ]:
d1=today.strftime("%d %B %y")
d1

In [ ]:
d2=today.strftime("%d-%b-%y")
d2

In [ ]:
d3=today.strftime("%d/%m/%y")
d3

In [ ]:
time.localtime()

In [ ]:
time.gmtime()

In [ ]:
from tkinter import *
tk=Tk()
canvas=Canvas(tk,width=400,height=400)
canvas.pack()
canvas.create_arc(10,10,200,100,extent=180,style=ARC)
tk.mainloop()

### Python Libraries for Data Analysis
- Many popular Python toolboes/Libraries:
    - Numpy
    - SciPy
    - SciKit-Learn
    - Pandas
- Visualization libraries
    - Matplotlib
    - Seaborn
    - Plotly
    

In [ ]:
import numpy as np
ar=np.array([[1,2,3],[4,5,6]])
ar

In [ ]:
np.random.randn(2,3)

In [ ]:
np.random.rand(4,2)

In [ ]:
np.random.randint(2,10)

In [ ]:
ar2=np.array([[5,8,2],[9,4,2]])
ar2

In [ ]:
ar*ar2

In [ ]:
ar-ar2

In [ ]:
ar+ar2

In [ ]:
ar*4

In [ ]:
ar-5

In [ ]:
1/ar2

In [ ]:
flar=np.array([[2.4,5.0,9.2],[9.4,3.2,3.1]])
flar

In [ ]:
ar>flar

In [ ]:
rn=np.random.randn(2,5)
rn

In [ ]:
rn*10

In [ ]:
rn+rn+rn

In [ ]:
rn*2

In [ ]:
rn**2

In [ ]:
arr=np.arange(15)
arr

In [ ]:
arr[4]

In [ ]:
arr[5:12]=16
arr

In [ ]:
ar_sl=arr[5:12]
ar_sl

In [ ]:
arr[6]

In [ ]:
ar2d=np.array([(5,7,2),(3,9,5),(4,2,9),(5,9,2),(9,3,6)])
ar2d

In [ ]:
ar2d[2:,0:]

In [ ]:
ar2d[1:4,1:3]

In [ ]:
ar2d[1:3,1:]

In [ ]:
ar2d[1:,:]

In [ ]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4)
names=='Bob'

In [158]:
data=np.random.randn(7,4)
data

array([[-0.79743894, -1.61252016, -0.79988308, -1.23492479],
       [ 0.52912209, -0.12411299, -1.24175599, -2.41221953],
       [ 0.37526015,  0.12720331, -0.49994907, -0.00737096],
       [ 0.00724481,  0.35217361, -0.70831534,  0.65787581],
       [-0.55032179,  1.36648625,  0.09925931, -0.29357354],
       [ 0.82677124,  1.18838047, -0.35364102,  0.88239944],
       [-0.14257151, -0.70249887, -1.10692804,  0.6238233 ]])

In [168]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [170]:
data[names=='Bob']

array([[ 0.46611857,  0.02206012, -1.08857012, -0.87438653],
       [ 0.05981878,  1.52506839, -1.21171383, -1.49001489]])

In [171]:
data[names=='Bob',2:]

array([[-1.08857012, -0.87438653],
       [-1.21171383, -1.49001489]])

In [172]:
data[names=='Bob',3]

array([-0.87438653, -1.49001489])

In [191]:
names!='Bob'

array([False,  True,  True, False,  True,  True,  True])